services:
  - type: web
    name: synergy-rk-backend
    env: docker
    rootDir: ./backend
    plan: free
    autoDeploy: true
    domains:
      - api.synergyrkofficial.com
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

